name: tekartik_idb_provider
version: 0.1.0
description: Provider pattern on top of indexeddb
dependencies:
  tekartik_core:
    git: git://github.com/alextekartik/tekartik_core.dart
  idb_shim: any
  collection: any
dev_dependencies:
  test: any
  dev_test: any
dependency_overrides:
#  idb_shim:
#    git: https://github.com/alextekartik/idb_shim.dart
