name: tekartik_idb_provider
version: 0.3.0
description: Provider pattern on top of indexeddb
environment:
  sdk: '>=2.1.0-dev <3.0.0'
dependencies:
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
  idb_shim: '>=1.7.0'
  collection: any
dev_dependencies:
  process_run: '>=0.10.1'
  test: any
  dev_test: any
  build_runner: '>=0.9.0'
  build_test: '>=0.10.2'
  build_web_compilers: '>=0.4.0'
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
dependency_overrides:
#  idb_shim:
#    git: https://github.com/alextekartik/idb_shim.dart
